port: 7890
socks-port: 7891
mode: rule
external-controller: 127.0.0.1:9090
allow-lan: false
dns:
  enable: false
tun:
  enable: false
  stack: system
log-level: debug
proxies:
  - name: 01
    type: socks5
    server: 127.0.0.1
    port: 1080
proxy-groups:
  - name: Proxy
    type: select
    proxies:
      - 01
rules:
  - MATCH,Proxy
